# Generated by Django 4.0.5 on 2022-06-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='api.director'),
            preserve_default=False,
        ),
    ]
